{
 "title": "Page metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "base", "label": "sitespeed_io", "query": "sitespeed_io" },
   { "name": "path", "query": "$base.*" },
   { "name": "testname", "query": "$base.$path.*" },
   {
    "name": "group",
    "label": "domain",
    "query": "$base.$path.$testname.pageSummary.*"
   },
   {
    "name": "page",
    "query": "$base.$path.$testname.pageSummary.$group.*"
   },
   {
    "name": "browser",
    "query": "$base.$path.$testname.pageSummary.$group.$page.*"
   },
   {
    "name": "connectivity",
    "query": "$base.$path.$testname.pageSummary.$group.$page.$browser.*"
   },
   {
    "name": "function",
    "query": "min, mean,median,p90,max,stddev"
   },
   { "name": "resulturl", "query": "http://localhost:3002" },
   { "name": "screenshottype", "query": "png" }
  ]
 },
 "panels": [
  {
   "title": "Per run",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "Show data from each individual run from the last seven days."
     }
    },
    {
     "title": "First visual change",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(sitespeed_io.$path.$testname.run.$group.$page.$browser.$connectivity.browsertime.visualMetrics.FirstVisualChange, 'First Visual Change')"
      },
      {
       "target": "alias(sitespeed_io.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.median, 'Median')"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(sitespeed_io.$path.$testname.run.$group.$page.$browser.$connectivity.browsertime.googleWebVitals.largestContentfulPaint, 'Largest Contentful Paint')"
      },
      {
       "target": "alias(sitespeed_io.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.median, 'Median')"
      }
     ]
    },
    {
     "title": "Time to first byte",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(sitespeed_io.$path.$testname.run.$group.$page.$browser.$connectivity.browsertime.timings.ttfb, 'TTFB')"
      },
      {
       "target": "alias(sitespeed_io.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.median, 'Median')"
      }
     ]
    },
    {
     "title": "CPU benchmark",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(sitespeed_io.$path.$testname.run.$group.$page.$browser.$connectivity.browsertime.browser.cpuBenchmark, 'CPU benchmark')"
      },
      {
       "target": "alias(sitespeed_io.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.browser.cpuBenchmark.median, 'Median')"
      }
     ]
    }
   ]
  },
  { "title": "Page metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Meta data for the test",
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 2 },
   "options": {
    "content": "{{#each data}}\n{{{friendlyHTML}}}\n\n{{#if title}}\n---\n**{{{title}}}**\n\n{{{description}}}\n{{/if}}\n\n{{/each}}"
   },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "experimentalGroupByField": "*",
     "fields": [
      { "jsonPath": "description  ", "language": "jsonata", "name": "description" },
      { "jsonPath": "title", "language": "jsonata", "name": "title" },
      { "jsonPath": "friendlyHTML", "language": "jsonata", "name": "friendlyHTML" }
     ],
     "method": "GET",
     "urlPath": "/$testname/$base.$path.$group.$page.$browser.$connectivity.json"
    }
   ]
  },
  {
   "title": "Page Vitals",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Screenshot from last run",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "options": {
    "content": "<a href=\"$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype\">\n<img src=\"$resulturl/$testname/$group.$page.$browser.$connectivity.$screenshottype\"></a>"
   },
   "targets": [
    {
     "target": "aliasByNode($base.$path.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 8)"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint",
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "options": {
    "content": "<a href=\"$resulturl/$testname/$group.$page.largestContentfulPaint.$browser.$connectivity.$screenshottype\">\n<img src=\"$resulturl/$testname/$group.$page.largestContentfulPaint.$browser.$connectivity.$screenshottype\"></a>"
   },
   "targets": [
    {
     "target": "alias($base.$path.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domElements, 'DOM elements')"
    }
   ]
  },
  {
   "title": "Visual Metrics [$function]",
   "type": "timeseries",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.$function, 'TTFB')"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.Heading.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, 11)"
    },
    {
     "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestContentfulPaint.$function, 11)"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 'Fully Loaded')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.lastLongTask.$function, 'Last CPU long task')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.transferSize, 'Total Transfer Size')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 'Requests')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domElements, 'DOM Elements')"
    }
   ]
  },
  {
   "title": "Google Web Vitals",
   "type": "text",
   "description": "Metrics that Google thinks is important for a good user experience.",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.paintTiming.first-contentful-paint.$function, 'First Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 'Largest Contentful Paint')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.pageinfo.cumulativeLayoutShift.$function, 'Cumulative Layout Shift')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalBlockingTime.$function, 'Total Blocking Time')"
    }
   ]
  },
  {
   "title": "Visual Metrics",
   "type": "text",
   "description": "When is elements painted within the viewport. The metrics comes from analysing a video of the browser screen.",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 'First Visual Change')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.Heading.$function, 'Largest Heading')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LargestImage.$function, 'Largest Image')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.LastVisualChange.$function, 'Last Visual Change')"
    }
   ]
  },
  {
   "title": "Coach Score",
   "type": "stat",
   "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.bestpractice.score, 'Best practice')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.performance.score, 'Performance')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.privacy.score, 'Privacy')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.score, 'Total')"
    }
   ]
  },
  {
   "title": "Axe violations [enable with --axe.enable]",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.critical.$function, 'Critical')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.serious.$function, 'Serious')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.moderate.$function, 'Moderate')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.minor.$function, 'Minor')"
    }
   ]
  },
  {
   "title": "CPU  [Chrome only, enable with --cpu]",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstContentfulPaint.tasks.$function, 'Long tasks before FCP')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.max, 'Number of long tasks')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.max, 'Longest long task')"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.lastLongTask.$function, 'Last long task')"
    }
   ]
  },
  { "title": "Page history", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
   "options": {
    "content": "Showing how the page is built over time."
   }
  },
  {
   "title": "Total page size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentSize, 'Content size')"
    },
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.transferSize, 'Transfer size')"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.requests, 'Requests')"
    }
   ]
  },
  {
   "title": "DOM elements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.pageinfo.domElements.$function, 'DOM elements')"
    }
   ]
  },
  {
   "title": "Total domains",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.totalDomains, 'Total domains')"
    }
   ]
  },
  {
   "title": "Page size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 48 },
     "options": {
      "content": "Transfer size is the size over the wire when the data is transfered to the browser (hopefully compressed). Content size is the size unpacked in the browser. "
     }
    },
    {
     "title": "HTML size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.html.contentSize, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.html.transferSize, 11)"
      }
     ]
    },
    {
     "title": "JavaScript size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.javascript.contentSize, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.javascript.transferSize, 11)"
      }
     ]
    },
    {
     "title": "CSS size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.css.contentSize, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.css.transferSize, 11)"
      }
     ]
    },
    {
     "title": "Image size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.image.contentSize, 11)"
      }
     ]
    },
    {
     "title": "Content size per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.contentSize, 10)"
      }
     ]
    },
    {
     "title": "Transfer size per type",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.transferSize, 10)"
      }
     ]
    }
   ]
  },
  {
   "title": "Elements that needs recalculate style before ... [Chrome only, enable with --cpu]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 49 },
     "options": {
      "content": "Keep track of the number of element that is affected by recalcualte style before first contentful paint and largest contentful paint."
     }
    },
    {
     "title": "Elements affected by recalculated styles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.renderBlocking.recalculateStyle.beforeFCP.elements.$function, 'Elements before First Contentful Paint (FCP)')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.renderBlocking.recalculateStyle.beforeLCP.elements.$function, 'Elements before Largest Contentful Paint (LCP)')"
      }
     ]
    },
    {
     "title": "Time spent in recalculated styles before FCP/LCP",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.renderBlocking.recalculateStyle.beforeFCP.durationInMillis.$function, 'Time in recalculate style before First Contentful Paint (FCP)')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.renderBlocking.recalculateStyle.beforeLCP.durationInMillis.$function, 'Time in recalculate style before Largest Contentful Paint (LCP)')"
      }
     ]
    }
   ]
  },
  {
   "title": "Largest Contentful Paint and Cumulative Layout Shift screenshot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
     "options": {
      "content": "Screenshots showing what part of the page is the largest contentful paint (LCP) (the red area) and content that is moved around (cumulative layout shift)."
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 0, "y": 62 },
     "options": {
      "content": "Largest contentful paint (LCP) - the largest area painted is in the red area."
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 12, "x": 12, "y": 62 },
     "options": {
      "content": "Cumulative layout shift (CLS) - red is the area that moved."
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "options": {
      "content": "<a href=\"$resulturl/$testname/$base.$path.$group.$page.largestContentfulPaint.$browser.$connectivity.$screenshottype\">\n<img src=\"$resulturl/$testname/$base.$path.$group.$page.largestContentfulPaint.$browser.$connectivity.$screenshottype\"></a>\n\n\n"
     }
    },
    {
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "options": {
      "content": "<a href=\"$resulturl/$testname/$base.$path.$group.$page.layoutShift.$browser.$connectivity.$screenshottype\">\n<img src=\"$resulturl/$testname/$base.$path.$group.$page.layoutShift.$browser.$connectivity.$screenshottype\"></a>\n\n\n"
     }
    }
   ]
  },
  {
   "title": "Coach history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
     "options": {
      "content": "The coach helps you find performance problems on your web page. "
     }
    },
    {
     "title": "Coach Score",
     "type": "timeseries",
     "description": "The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.The performance score (0-100) calculated by the [Coach](https://www.sitespeed.io/documentation/coach/) using performance best practices.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.bestpractice.score, 'Best practice')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.performance.score, 'Performance')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.privacy.score, 'Privacy')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.score, 'Total')"
      }
     ]
    }
   ]
  },
  {
   "title": "Main document timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 74 },
     "options": {
      "content": "Main document timings is the timings for downloading the main HTML page."
     }
    },
    {
     "title": "Main document timings",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.mainDocumentTimings.*.$function, 12)"
      }
     ]
    }
   ]
  },
  {
   "title": "Axe history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Axe violations",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.critical.$function, 'Critical')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.serious.$function, 'Serious')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.moderate.$function, 'Moderate')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.axe.violations.minor.$function, 'Minor')"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Web Vitals trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function, '24h'), 'Last 24 hours')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.firstContentfulPaint.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, '24h'), 'Last 24 hours')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.largestContentfulPaint.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.totalBlockingTime.$function, '24h'), 'Last 24 hours')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.totalBlockingTime.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function, '24h'), 'Last 24 hours')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.googleWebVitals.cumulativeLayoutShift.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    }
   ]
  },
  {
   "title": "Google Web Vitals history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Contentful Paint (FCP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.paintTiming.first-contentful-paint.$function, 'FCP')"
      }
     ]
    },
    {
     "title": "Cumulative Layout Shift (CLS)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.pageinfo.cumulativeLayoutShift.$function, 'CLS')"
      }
     ]
    },
    {
     "title": "Largest Contentful Paint (LCP)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 'LCP')"
      }
     ]
    },
    {
     "title": "Total Blocking Time (TBT)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalBlockingTime.$function, 'TBT')"
      }
     ]
    }
   ]
  },
  {
   "title": "Navigation Timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 56 },
     "options": {
      "content": "Data that is collected using the [Navigation Timing API](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API) (the same data as you can collect from real users. Use it to compare changes in data from our real users."
     }
    },
    {
     "title": "Navigation Timings  [$function]",
     "type": "timeseries",
     "description": "Metrics collected from theNavigation Timing API",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.navigationTiming.*.$function, 12)"
      }
     ]
    }
   ]
  },
  {
   "title": "Even more page statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "description": "The document height in pixels.",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.documentHeight, 'Document height (pixels)')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 6, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.totalDomains, 'Number of domains')"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The total number of iframes used on the page.",
     "gridPos": { "h": 4, "w": 4, "x": 11, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.iframes, 'Number of iframes')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 15, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.cookies, 'Number of cookies')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.cookies, 'Third Party Cookies')"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The $function cache expire time of all responses for the page.",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.expireStats.$function, 'The $function cache expire time of all responses')"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The $function last modified time of all responses for the page.",
     "gridPos": { "h": 4, "w": 4, "x": 5, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.lastModifiedStats.$function, 'The $function last modified time of all responses')"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The average DOM depth of the page.",
     "gridPos": { "h": 4, "w": 3, "x": 9, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.avg, 'Average DOM depth')"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The max depth of DOM elements on the page.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.domDepth.max, 'Max DOM depth')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.localStorageSize, 'Local storage size')"
      }
     ]
    },
    {
     "type": "stat",
     "description": "The total number of iframes used on the page.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.coach.advice.info.scripts, 'Number of scripts')"
      }
     ]
    }
   ]
  },
  {
   "title": "Request history",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of requests per type",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.contentTypes.*.requests, 10)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Long Tasks [Chrome only, enable with --cpu]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
     "options": {
      "content": "Data collected using the [CPU long tasks API](https://developer.mozilla.org/en-US/docs/Web/API/Long_Tasks_API). The long tasks depends on the CPU used on the device that runs the tests so you can only compare metrics using the exact same device. Use the data to see trends."
     }
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function, 'Long Tasks')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 5, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstContentfulPaint.tasks.$function, 'Long Tasks Before FCP')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalBlockingTime.$function, 'Total Blocking Time')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.max, 'Longest Long Task')"
      }
     ]
    },
    {
     "title": "CPU Long Tasks",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.tasks.$function, 'Long Tasks')"
      }
     ]
    },
    {
     "title": "CPU Long Tasks Before FCP",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 5, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.beforeFirstContentfulPaint.tasks.$function, 'Long Tasks Before FCP')"
      }
     ]
    },
    {
     "title": "Total Blocking Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 11, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.totalBlockingTime.$function, 'Total Blocking Time')"
      }
     ]
    },
    {
     "title": "Longest Long Task",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.longTasks.durations.max, 'Longest Long Task')"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Details [Chrome only, enable with --cpu]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 73 },
     "options": {
      "content": "Data collected from the Chrome trace log whgere we can see where the browser spends it time creating the page."
     }
    },
    {
     "title": "CPU [Chrome only]",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.categories.*.median, 12)"
      }
     ]
    },
    {
     "title": "CPU time spent per event",
     "type": "timeseries",
     "description": "The CPU metrics are collected from Chrome when you add --chrome.timeline to your run. The trace log is analyzed and sorted by type.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "currentAbove(aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cpu.events.*.median, 12), 1)"
      }
     ]
    }
   ]
  },
  {
   "title": "JavaScript heap [Chrome only]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "JS Heap size [Chrome only]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cdp.performance.JSHeapTotalSize.$function, 12)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.cdp.performance.JSHeapUsedSize.$function, 12)"
      }
     ]
    }
   ]
  },
  {
   "title": "Delta TTFB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 62 },
     "options": {
      "content": "Delta TTFB metrics is metrics where we remove the time to first byte from the metrics. If we have metrics that are unstable because of unstable TTFB these metrics can be stable."
     }
    },
    {
     "title": "Visual Metrics [$function]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.deltaToTFFB.*.$function, 11)"
      }
     ]
    }
   ]
  },
  {
   "title": "Carbon emission (enable with --sustainable.enable)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.sustainable.totalCO2.$function, 'Total C02')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.sustainable.co2PerPageView.$function, 'CO2 Per Page View')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.sustainable.co2FirstParty.$function, 'CO2 First Party')"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "massg" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.sustainable.co2ThirdParty.$function, 'CO2 Third Party')"
      }
     ]
    }
   ]
  },
  {
   "title": "Timings, element timings and user timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 62 },
     "options": {
      "content": "Performance metrics that you can add yourself by annotating your page. We automatically collect [User Timing API](https://developer.mozilla.org/en-US/docs/Web/API/User_Timing_API) metrics and [Element Timing API metrics](https://developer.mozilla.org/en-US/docs/Web/API/Element_timing_API) (when elements are painted on the screen)."
     }
    },
    {
     "title": "Timings  [$function]",
     "type": "timeseries",
     "description": "Timing metrics collected using browser APIs like the Navigation Timing API.",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.firstPaint.$function, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.largestContentfulPaint.renderTime.$function, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.loadEventEnd.$function, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.domContentLoadedTime.$function, 12)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, 12)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.timeToContentfulPaint, 11)"
      },
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.timeToFirstInteractive, 11)"
      }
     ]
    },
    {
     "title": "Element Timings  [$function]",
     "type": "timeseries",
     "description": "Timings collected using the [Element Timing API](https://wicg.github.io/element-timing/).",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.elementTimings.*.renderTime.$function, 12)"
      }
     ]
    },
    {
     "title": "User Timings Marks  [$function]",
     "type": "timeseries",
     "description": "All User Timing marks created on the page using the [User Timing API](https://www.w3.org/TR/user-timing/).",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.marks.*.$function, 13)"
      }
     ]
    },
    {
     "title": "User Timings Measures [$function]",
     "type": "timeseries",
     "description": "All User Timing marks created on the page using the [User Timing API](https://www.w3.org/TR/user-timing/).",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.userTimings.measures.*.$function, 13)"
      }
     ]
    }
   ]
  },
  {
   "title": "Main document timings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 63 },
     "options": {
      "content": "Main document timings is the timings for downloading the main HTML page."
     }
    },
    {
     "title": "Main document timings [$function]",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.mainDocumentTimings.*.$function, 12)"
      }
     ]
    }
   ]
  },
  {
   "title": "Timing trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "First Visual Change",
     "type": "timeseries",
     "description": "The Visual Metrics are collected by recording and analysing a video of the screen.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), 11)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Speed Index",
     "type": "timeseries",
     "description": "The Visual Metrics are collected by recording and analysing a video of the screen.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), 11)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.SpeedIndex.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "TTFB/Server response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, '24h'), 'TTFB')"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.pageTimings.serverResponseTime.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "Fully Loaded",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode(movingAverage($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), 11)"
      },
      {
       "target": "alias(timeShift(movingAverage($base.$path.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.fullyLoaded.$function, '24h'), '7d'), 'One week earlier')"
      }
     ]
    },
    {
     "title": "First Visual Change History",
     "type": "timeseries",
     "description": "The Visual Metrics are collected by recording and analysing a video of the screen.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.visualMetrics.FirstVisualChange.$function, 11)"
      }
     ]
    }
   ]
  },
  {
   "title": "Cookies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cookies",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.thirdParty.cookies, 'Third Party Cookies')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.firstParty.cookies, 'First Party Cookies')"
      }
     ]
    }
   ]
  },
  {
   "title": "Third party",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Third party request by category",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.thirdparty.category.*.requests.$function, 10)"
      }
     ]
    },
    {
     "title": "Third party tools by category",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.thirdparty.category.*.tools.$function, 10)"
      }
     ]
    },
    {
     "title": "CPU time spent per tool/domain - enable using --thirdParty.cpu  [Chrome only]",
     "type": "timeseries",
     "description": "Activate by adding --thirdParty.cpu  to to your run.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.thirdparty.tool.*.cpu, 10)"
      }
     ]
    }
   ]
  },
  {
   "title": "Response codes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response codes",
     "type": "timeseries",
     "description": "All requests and their HTTP Status Code.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.pagexray.responseCodes.*, 10)"
      }
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Console error and warnings",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.console.*.$function, 11)"
      }
     ]
    },
    {
     "title": "Errors collecting the metrics",
     "type": "timeseries",
     "description": "Show number of errors from Browsertime and other tools.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.errors.$function, 11)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU benchmark variation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 71 },
     "options": {
      "content": "Variation over time in the in CPU benchmark metric (how long time it takes to run a JavaScript loop). Use this metric to make sure the CPU speed is constant over time."
     }
    },
    {
     "title": "CPU benchmark",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.browser.cpuBenchmark.min, 'min')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.browser.cpuBenchmark.median, 'median')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.browser.cpuBenchmark.max, 'max')"
      }
     ]
    },
    {
     "title": "CPU benchmark stddev",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.browser.cpuBenchmark.stddev, 'stddev')"
      }
     ]
    }
   ]
  },
  {
   "title": "TTFB variation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 72 },
     "options": {
      "content": "Variation over time in the time to first byte metric (TTFB). Use it to make sure TTFB is stable over time."
     }
    },
    {
     "title": "TTFB",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.min, 'min')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.median, 'median')"
      },
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.max, 'max')"
      }
     ]
    },
    {
     "title": "TTFB stddev",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "alias($base.$path.$testname.pageSummary.$group.$page.$browser.$connectivity.browsertime.statistics.timings.ttfb.stddev, 'stddev')"
      }
     ]
    }
   ]
  }
 ]
}